baseurl = "https://theseusf.github.io/"
languageCode = "en-us"
title = "å‘¨æœ«æ‚è´§é“ºğŸ’¤"
theme = "hugo-tania"
paginate = 30

# disqusShortname = "https-hugo-tania-netlify-app"

[params]
  toc = true
  
  # Emoji will show before the blog title on site navbar.
  titleEmoji  = ""

  # Logo will show before the blog title on site navbar.
  titleLogo = "https://avatars.githubusercontent.com/u/22488581?s=96&v=4"

  # Enable float footnotes.
  # Default to true
  enableFootnotes = true

  siteName = "å‘¨æœ«æ‚è´§é“ºğŸ’¤"
  siteDesc = "Thanks for all the fish"
  author = "å‘¨æœ«ğŸ’¤"

  [params.colorScheme]
    # Enable toggle colorScheme
    # Default to true
    toggle = true
    # Default colorScheme
    # Default to auto
    # default = auto

  # Limit how many categories filter show above search input.
  # Default to 5
  maxCategoryToShow = 10

  # Show your social information with icon on index bio with `_index.md` content.
  [params.socialOptions]
    dev-to = ""
    email = ""
    facebook = ""
    github = ""
    instagram = ""
    linkedin = ""
    medium = ""
    stack-overflow = ""
    steam = ""
    telegram = ""
    twitter = ""
    twitch = ""
    whatsapp = ""
  
  # Comments settigns
  [params.comments]
    enabled = true
    provider = "disqus"

[menu]
[[menu.header]]
  name = "Articles"
  url = "/articles/"
[[menu.footer]]
    name = "RSS"
    url = "/index.xml"

[markup]
[markup.highlight]
  noClasses = false
  lineNos = true
[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]